

#GET http://localhost:4004/odata/v4/productshop/product


POST http://localhost:4004/odata/v4/productshop/product
Content-Type: application/json

{ 
    "name" : "Maruti Alto"
}




#GET http://localhost:4004/browseshop/supplier

#GET http://localhost:4004/odata/v4/productshop/product?$expand=ord


#GET http://localhost:4004/odata/v4/productshop/supplier?$expand=product($select=name,stock)


#GET http://localhost:4004/odata/v4/productshop/addNumberFunction(a=4,b=8)

#PUT http://localhost:4004/odata/v4/productshop/product('1')



#POST http://localhost:4004/odata/v4/productshop/addNumberAction







